app = 'baby-data'
primary_region = 'cdg'

[build]
  dockerfile = "/Dockerfile"

[deploy]
  strategy = "canary"

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/healthcheck"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
