# fly.toml app configuration file generated for baby-data on 2024-12-19T23:15:15+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'baby-data'
primary_region = 'cdg'

[build]
  dockerfile = "/Dockerfile"

[deploy]
  strategy = "canary"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
